spring.application.name=Medical-Office-Reservation-System
spring.datasource.url=jdbc:postgresql://localhost:5432/medical_office_reservation_system
spring.datasource.username=postgres
spring.datasource.password=example
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto= update